export const DRILL_SERGEANT_INSULTS = [
  "MOVE, CURSOR! I'VE SEEN LOADING SPINNERS WITH MORE INITIATIVE!",
  "YOU CALL THAT AN APPROACH? A HOUSEPLANT COULD FLANK ME!",
  "YOUR HAND–EYE COORDINATION HAS FILED FOR EARLY RETIREMENT!",
  "I'VE MET POP-UP ADS WITH BETTER TACTICAL INSTINCTS!",
  "THAT POINTER IS ALL HAT AND NO CLICK, RECRUIT!",
  "MY GRANDMOTHER USES A TRACKPAD WITH MORE AUTHORITY—AND SHE'S A FAX MACHINE!",
  "WERE YOU AIMING FOR ME OR APPLYING FOR A DESK JOB?",
  "YOU COULDN'T CLICK WATER IF YOU FELL OUT OF A BOAT!",
  "THE BUTTON IS RED, RECRUIT, NOT INVISIBLE. YET.",
  "I'VE SEEN GOVERNMENT WEBSITES MOVE FASTER THAN THAT!",
  "YOUR CURSOR HAS THE TACTICAL PRECISION OF A WET BREADSTICK!",
  "ARE WE CLICKING TODAY, OR ARE WE WRITING A MEMO ABOUT IT?",
] as const;

export const HIDING_TAUNTS = [
  "OUTSTANDING! YOU SCARED IT INTO ANOTHER ZIP CODE!",
  "BUTTON'S GONE, RECRUIT! FILE A MISSING-COMPETENCE REPORT!",
  "IT'S HIDING. EVEN THE BUTTON IS EMBARRASSED FOR YOU!",
] as const;

export const MERCY_TAUNT = "MERCY WINDOW! TWO SECONDS! MAKE YOUR ANCESTORS SLIGHTLY LESS EMBARRASSED!";
